openapi: 3.0.0

info:
  title: AgriFed API
  description: API for AgriFed
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local Development

tags:
  - name: Collectivites
    description: Collectivités au sein de la fédération
  - name: Membres
  - name: Cotisations

paths:
  /membres:
    get:
      tags:
        - Membres
      summary: Membres
      description: Returns all members
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Membre'
    post:
      tags:
        - Membres
      summary: Add a new member
      description: Adds a new member to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembreCreationRequest'
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Membre'
                example:
                  message: Cotisation créée
        400:
          description: Cotisation non créée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Cotisation non créée

    delete:
      tags:
        - Membres
      summary: Delete a member
      description: Deletes a member from the database
      responses:
        204:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message
                example:
                  message: Membre deleted
  /cotisations:
    post:
      tags:
        - Cotisations
      summary: Créer une cotisation
      description: Créer une cotisation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CotisationRequest'
      responses:
        201:
          description: Cotisation créée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message
                example:
                  message: Cositation créée
  /health:
    get:
      summary: Health Check
      description: Returns health check status
      responses:
        200:
          description: Health check status
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Hello world

  /collectivites:
    post:
      tags:
        - Collectivites
      description: Create a new collectivite
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectiviteCreation'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collectivite'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
    CollectiviteCreation:
      allOf:
        - $ref: '#/components/schemas/Collectivite'
        - type: object
          properties:
            specialite_agricole:
              type: string
              description: Spécialité agricole
            autorisation_federation:
              type: boolean
              description: Autorisation de la fédération
    MembreCreationRequest:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/Membre'
          - type: object
            properties:
              date_naissance:
                type: string
                format: date
                description: Date de naissance du membre
              paiment:
                oneOf:
                  - $ref: '#/components/schemas/CompteBancaire'
                  - $ref: '#/components/schemas/MobileMoney'
    CotisationRequest:
      type: object
      properties:
        proprietaire:
          $ref: '#/components/schemas/Membre'
        type_cotisation:
          type: string
          enum:
            - mensuelles
            - annuelles
            - ponctuelle
        montant:
          type: number
          format: float
          description: Montant de la cotisation
        date_encaissement:
          type: string
          format: date
          description: Date de l'encaissement
        mode_paiment:
          oneOf:
            - $ref: '#/components/schemas/CompteBancaire'
            - $ref: '#/components/schemas/MobileMoney'
            - $ref: '#/components/schemas/Espece'
    Espece:
      type: object
      properties:
        nom_personne:
          type: string
          description: Nom de la personne
        montant:
          type: number
          format: float
          description: Montant de la cotisation
    CompteBancaire:
      type: object
      properties:
        titulaire:
          type: string
        nom_banque:
          type: string
          enum:
            - BRED
            - MCB
            - BMOI
            - BOA
            - BGFI
            - AFG
            - ACCESS BANQUE
            - BAOBAB
            - SIPEM
        numero:
          type: object
          properties:
            code_banque:
              type: integer
            code_guichet:
              type: integer
            numero_compte:
              type: integer
            cle_rib:
              type: integer
        montant:
          type: number
          format: float
    MobileMoney:
      type: object
      properties:
        titulaire:
          type: string
        numero:
          type: string
        service_mobile_money:
          type: string
          enum:
            - ORANGE MONEY
            - MVOLA
            - AIRTEL MONEY
        montant:
          type: number
          format: float
    Collectivite:
      type: object
      properties:
        nom:
          type: string
          description: Nom de la collectivité
        numero:
          type: string
          description: Numéro de la collectivité
        specialite_agricole:
          type: string
          description: Spécialité agricole
        date_creation:
          type: string
          format: date
          description: Date de création de la collectivité
        ville:
          type: string
          description: Ville de la collectivité
        membres:
          type: array
          items:
            $ref: '#/components/schemas/Membre'
        president:
          $ref: '#/components/schemas/Membre'
        president_adjoint:
          $ref: '#/components/schemas/Membre'
        tresorier:
          $ref: '#/components/schemas/Membre'
        secretaire:
          $ref: '#/components/schemas/Membre'
    Membre:
      type: object
      properties:
        nom:
          type: string
          description: Nom du membre
        prenom:
          type: string
          description: Prénom du membre
        genre:
          type: string
          description: Genre du membre
        adresse:
          type: string
          description: Adresse du membre
        metier:
          type: string
          description: Métier du membre
        telephone:
          type: string
          description: Téléphone du membre
        email:
          type: string
          description: Email du membre
        date_adhesion:
          type: string
          format: date
          description: Date d'adhésion du membre
        poste_specifique:
          type: string
          description: Poste spécifique du membre
          enum:
            - President
            - President Adjoint
            - Tresorier
            - Secretaire
            - Membre confirme
            - Membre junior
    Federation:
      type: object
      properties:
        president:
          $ref: '#/components/schemas/Membre'
        president_adjoint:
          $ref: '#/components/schemas/Membre'
        tresorier:
          $ref: '#/components/schemas/Membre'
        secretaire:
          $ref: '#/components/schemas/Membre'
        collectivites:
          type: array
          items:
            $ref: '#/components/schemas/Collectivite'
