openapi: 3.0.0

info:
  title: AgriFed API
  description: API for AgriFed
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local Development

tags:
  - name: Assuidite

paths:

  /presence/{evenement}:
    post:
      tags:
        - Assuidite
      description: Creer la présence durant un evenement
      parameters:
        - in: path
          name: evenement
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PresenceEvenement'
      responses:
        200:
          description: Présence durant un evenement
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PresenceEvenement'
    get:
      tags:
        - Assuidite
      description: Obtenir la présence durant un evenement
      parameters:
        - in: path
          name: evenement
          required: true
          schema:
            type: string
      responses:
        200:
          description: Présence durant un evenement
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PresenceEvenement'

  /presence/{id}:
    get:
      tags:
        - Assuidite
      summary: Obtenir la présence d'un membre
      description: Obtenir la présence d'un membre
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Présence d'un membre
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssuiditeResponse'
  /health:
    get:
      summary: Health Check
      description: Returns health check status
      responses:
        200:
          description: Health check status
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Hello world

components:
  schemas:
    PresenceEvenement:
      type: object
      properties:
        nom_evenement:
          type: string
          description: Nom de l'événement
        date_evenement:
          type: string
          format: date
          description: Date de l'événement
        membres_present:
          type: array
          items:
            $ref: '#/components/schemas/Membre'
        membres_absent:
          type: array
          items:
            $ref: '#/components/schemas/Membre'
    AssuiditeResponse:
      type: object
      properties:
        member:
          type: object
          $ref: '#/components/schemas/Membre'
        cotisation:
          type: number
          format: float
        nombre_presence:
          type: integer
        nombre_absence:
          type: integer
    CompteBancaire:
      type: object
      properties:
        titulaire:
          type: string
        nom_banque:
          type: string
          enum:
            - BRED
            - MCB
            - BMOI
            - BOA
            - BGFI
            - AFG
            - ACCESS BANQUE
            - BAOBAB
            - SIPEM
        numero:
          type: object
          properties:
            code_banque:
              type: integer
            code_guichet:
              type: integer
            numero_compte:
              type: integer
            cle_rib:
              type: integer
    MobileMoney:
      type: object
      properties:
        titulaire:
          type: string
        numero:
          type: string
        service_mobile_money:
          type: string
          enum:
            - ORANGE MONEY
            - MVOLA
            - AIRTEL MONEY
    Collectivite:
      type: object
      properties:
        nom:
          type: string
          description: Nom de la collectivité
        numero:
          type: string
          description: Numéro de la collectivité
        specialite_agricole:
          type: string
          description: Spécialité agricole
        date_creation:
          type: string
          format: date
          description: Date de création de la collectivité
        ville:
          type: string
          description: Ville de la collectivité
        membres:
          type: array
          items:
            $ref: '#/components/schemas/Membre'
        president:
          $ref: '#/components/schemas/Membre'
        president_adjoint:
          $ref: '#/components/schemas/Membre'
        tresorier:
          $ref: '#/components/schemas/Membre'
        secretaire:
          $ref: '#/components/schemas/Membre'
    Membre:
      type: object
      properties:
        nom:
          type: string
          description: Nom du membre
        prenom:
          type: string
          description: Prénom du membre
        genre:
          type: string
          description: Genre du membre
        adresse:
          type: string
          description: Adresse du membre
        metier:
          type: string
          description: Métier du membre
        telephone:
          type: string
          description: Téléphone du membre
        email:
          type: string
          description: Email du membre
        date_adhesion:
          type: string
          format: date
          description: Date d'adhésion du membre
        poste_specifique:
          type: string
          description: Poste spécifique du membre
          enum:
            - President
            - President Adjoint
            - Tresorier
            - Secretaire
            - Membre confirme
            - Membre junior
    Federation:
      type: object
      properties:
        president:
          $ref: '#/components/schemas/Membre'
        president_adjoint:
          $ref: '#/components/schemas/Membre'
        tresorier:
          $ref: '#/components/schemas/Membre'
        secretaire:
          $ref: '#/components/schemas/Membre'
        collectivites:
          type: array
          items:
            $ref: '#/components/schemas/Collectivite'
